language: python
python:
  - "2.7"


sudo: required
services:
  - docker

services:
    - docker

env:
    global:
        - DOCKER_VERSION=1.10.1-0~trusty


compiler:
  - gcc
  - clang

before_install:
  # list docker-engine versions
  - apt-cache madison docker-engine

  # upgrade docker-engine to specific version
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=${DOCKER_VERSION}


script:
  - ./scripts/build_ceed
  - docker version
  - ./scripts/build_containers
  - ./scripts/build_containers.ostro
  - docker images | grep codi | grep  test
  - docker images | grep toolchain | grep  test
  - docker images | grep zephyr | grep  test
  - docker images | grep ostrobuilder | grep  v1.0.0
  - ./scripts/run_containers
  - python tests.py

notifications:
  email:
    recipients:
    on_success: change
    on_failure: always
