language: python
python:
  - "2.7"


sudo: required
services:
  - docker

services:
    - docker

env:
    global:
        - DOCKER_VERSION=1.10.1-0~trusty


compiler:
  - gcc
  - clang

before_install:
  # list docker-engine versions
  - apt-cache madison docker-engine

  # upgrade docker-engine to specific version
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=${DOCKER_VERSION}


script:
#  - ./scripts/build_ceed
  - docker version
#  - ./scripts/build_containers
#  - docker images | grep codi | grep -q test
#  - docker images | grep toolchain | grep -q test
#  - docker images | grep zephyr | grep -q test
#  - ./scripts/run_containers
  - ./scripts/build_containers.ostro
# this is to populate shared dir and make sstate go outside for image speedup
  - ./scripts/bitbake.ostro zlib-native
  - echo 'SSTATE_DIR = "/ostro/ostro-shared/sstate"' >> ostro-shared/conf/ostro.conf
# we run in parts to avoid timeout
  - ./tests/helpers/Spitter.py -c "./scripts/bitbake.ostro glibc"
  - ./tests/helpers/Spitter.py -c "./scripts/bitbake.ostro linux-yocto
  - ./tests/helpers/Spitter.py -c "./scripts/bitbake.ostro ostro-image-noswupd""
# tests split up
  - python tests.py -f ostro

notifications:
  email:
    recipients:
    on_success: change
    on_failure: always
